#!/usr/bin/env python

import sys, socket, select, time, json, random

# Your ID number
my_id = sys.argv[1]

# The ID numbers of all the other replicas
replica_ids = sys.argv[2:]

# Connect to the network. All messages to/from other replicas and clients will
# occur over this socket
sock = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
sock.connect(my_id)

# A list maintained by the leader
last_heartbeat = [time.time()] * len(replica_ids)
last_heard = [time.time()] * len(replica_ids)
# a value maintained by a follower
last_heartbeat_to_me = time.time()


# The current term
current_term = 0
# Who you are voting for
# None if there is not currently an election
# If it's non None and there's no election,
# that's the leader
voted_for = None

# The number of votes for me to be leader this
# election cycle
votes_for_me = 0

# True if its election season/ we don't know who the leader is
election_season = False
# Log of all messages
log = []

discard = 0
election_temp_storage = []

state_machine = {}

commit_index = -1
last_applied = 0


#timeout time
time_out_threshold = 300


# True if you are currently the leader
is_leader = False

next_index = [0] * len(replica_ids)
last_match = [-1] * len(replica_ids)


def send_heartbeat():
	for dest in replica_ids:
		send_append_entries([], dest)

def send_append_entries(entries, dest):
	dest_index = replica_ids.index(dest)
	prev_log_index = next_index[dest_index] - 1
	prev_log_term = None

	if prev_log_index > -1:
		prev_log_term = log[prev_log_index]

	msg = {
		'src': my_id,
		'dst': dest,
		'type': 'append',
		'leader': my_id,
		'term': current_term,
		'prev_log_index': prev_log_index,
		'prev_log_term': prev_log_term,
		'entries': entries,
		'leader_commit': commit_index
	}

	sock.send(json.dumps(msg))


def recieve_append_entries(leader_term, leader_id, prev_log_index, prev_log_term, entries_to_add, leader_commit):
	global log, commit_index, voted_for, current_term, election_season


	# The leader is behind our term
	if current_term > leader_term:
		return [current_term, False, -1]

	# Remember who the leader is
	voted_for = leader_id
	is_leader = False
	election_season = False
	current_term = leader_term

	# The log is empty
	# So take entries as the log
	# If entries is empty, this preserves
	# the status quo
	if prev_log_index <= -1:

		log = entries
		return [current_term, True, len(log)]


	# If the log is shorter than the leader thought
	# request all of the logs we don't have
	if len(log) <= prev_log_index:
		return [current_term, False, len(log)]


	# If the last term we expected to match doesn't,
	# go back and ask for more logs
	if log[prev_log_index] != prev_log_term:
		return [current_term, False, prev_log_index - 1]


	# Log truncates to last agreed upon term
	log = log[:prev_log_index + 1]
	log.extend(entries)

	# Update our committed index
	if leader_commit > commit_index:
		commit_index =  min(leader_commit, len(log) - 1)



	return [current_term, True, len(log)]

# Handle the response from an append
def recieve_append_response(term, success, nextIndex, src_id):
	global current_term, voted_for, is_leader, last_heard

	# If my term is behind the response term, update mine
	# and relinquish leadership and do nothing more
	if term > current_term:
		current_term = term
		voted_for = src_id
		is_leader = False
		return



	replica_index = replica_ids.index(src_id)
	# Whether or not its a success, we've heard from them
	last_heard[replica_index] = time.time()

	# The append were successful!
	if success:
		next_index[replica_index] = nextIndex
		last_match[replica_index] = nextIndex - 1
	# The append failed,
	# let's try again earlier
	else:
		next_index[replica_index] = nextIndex


# Sends a response indicating whether the
# append entries was a success
def send_append_entries_response(resp, dest):
	term = resp[0]
	successful = resp[1]
	nextIndex = resp[2]

	resp = {
		'src': my_id,
		'dst': dest,
		'leader': dest,
		'type': 'app_response',
		'ok': successful,
		'term': term,
		'nextIndex': nextIndex
	}

	sock.send(json.dumps(resp))




# Starts an election from this machine
def start_election():
	global current_term, voted_for, votes_for_me, last_heartbeat_to_me, election_temp_storage, election_season, is_leader


	# If you're starting an election, fail any messages you got in the interim
	for temp in election_temp_storage:
		temp['type'] = 'redirect'
		# Take a guess
		temp['leader'] = random.choice(replica_ids)
		sock.send(json.dumps(temp))
	election_temp_storage = []


	election_season = True
	is_leader = False
	current_term += 1
	#print (str(my_id) + " starting election for term " + str(current_term))
	voted_for = my_id
	votes_for_me = 1
	last_heartbeat_to_me = time.time()
	send_vote_request()


# Sends a request to all other machines to vote
# for this machine for leader
def send_vote_request():
	global last_heartbeat
	last_log_index = len(log) - 1
	last_log_term = None
	if last_log_index is not -1:
		last_log_term = log[last_log_index]
	req = {
		'src': my_id,
		'dst': 'FFFF',
		'leader': 'FFFF',
		'type': 'election',
		'term': current_term,
		'last_log_index': last_log_index,
		'last_log_term': last_log_term
	}
	sock.send(json.dumps(req))


# Handles recieving a vote for a new leader
def recieve_vote_request(candidate_term, candidate_id, last_log_index, last_log_term):
	global voted_for, current_term, last_heartbeat_to_me, election_season

	if is_leader:
		return [current_term, False]

	if candidate_term < current_term:
		return [current_term, False]

	else:

		if candidate_term > current_term:
			election_season = True
			current_term = candidate_term
			voted_for = candidate_id

		#print(str(my_id) + " Recieved request to vote for " + str(candidate_id) + " in term " + str(current_term) + ", leader: " + str(voted_for))
		candidate_available = voted_for == None or voted_for == candidate_id
		log_up_to_date = last_log_index >= len(log) - 1
		if candidate_available and log_up_to_date:
			#print(str(my_id) + " voted for " + str(candidate_id) + " in term " + str(current_term))
			# So we don't start another election immediately after voting for
			# someone
			last_heartbeat_to_me = time.time()
			return [current_term, True]
		else:
			return [current_term, False]


# Sends a response back to the person we've
# recieved a vote request from
def send_vote_response(vote_results, destination):
	req = {
		'src': my_id,
		'dst': destination,
		'leader': 'FFFF',
		'type': 'election_vote',
		'term': vote_results[0],
		'vote_granted': vote_results[1]
	}
	sock.send(json.dumps(req))
	# Give a little time for the election to happen
	last_heartbeat_to_me = time.time() + 2

# Recieves a vote for this election
def recieve_vote_response(term, voted_for_me):
	global votes_for_me, is_leader, voted_for, current_term, last_match, next_index, election_season, election_temp_storage
	# If the vote is for a previous term, ignore it

	if term == current_term:
		if voted_for_me:
			votes_for_me += 1

			#print(str(my_id) + " got " + str(votes_for_me) + " votes in term " + str(current_term))

		votes_needed = ((len(replica_ids) + 1) / 2) + 1
		# If you have enough votes, seize power
		if votes_for_me >= votes_needed:
			is_leader = True
			voted_for = None
			current_term += 1
			election_season = False
			# Empty the election temp election temporary election_temp_storage
			for msg in election_temp_storage:
				msg['leader'] = my_id
				sock.send(json.dumps(msg))
			election_temp_storage = []
			last_heard = [time.time()] * len(replica_ids)


			#print("Election is over: " + str(my_id) + " is leader in term " + str(current_term))
			next_index = [len(log)] * len(replica_ids)
			last_match = [commit_index] * len(replica_ids)

			send_heartbeat()


# Returns the timestamp of the last time we had a quorum
def time_since_last_quorum():
	sorted_times = sorted(last_heard)
	quorum_index = len(replica_ids) / 2
	return time.time() - sorted_times[quorum_index]



# Finds the highest value the majority of the replicas
# are willing to commit to
def highest_agreed_match_index():
	follower_index = 0
	match_index = -1
	while follower_index < len(replica_ids):
		test_val = last_match[follower_index]
		higher_or_equal_count = 0
		for match_val in last_match:
			if match_val >= test_val:
				higher_or_equal_count += 1

		# More than half of the replicas are ready to move
		# the commit index forward

		if higher_or_equal_count >= (len(replica_ids)) / 2:
			match_index = max(match_index, test_val)

		follower_index += 1

	return match_index

# Sends a confirmation back if the
# entry was committed on a quorum of machines
def send_put_confirmation(dest, mid):
	ok_msg = {
		'src': my_id,
		'dst': dest,
		'leader': my_id,
		'type': 'ok',
		'MID': mid,
		}

	sock.send(json.dumps(ok_msg))

# Main loop
while True:

	# Leader general responsibilities
	if is_leader:

		#print("C: " + str(last_match))
		#print("N: " + str(next_index) )
		#print("L: " + str(len(log)))

		#Reliquish leadership
		if time_since_last_quorum() > time_out_threshold:
			start_election()



		follower_index = 0
		while follower_index < len(replica_ids):
			replica_id = replica_ids[follower_index]

			time_since_last_heartbeat = time.time() - last_heartbeat[follower_index]
			time_since_in_ms = time_since_last_heartbeat * 1000

			last_log_index = len(log) - 1
			next_index_for_follower = next_index[follower_index]

			#Sends logs to followers if necesary
			if last_log_index >= next_index_for_follower and time_since_in_ms > 1:
				entries = log[next_index_for_follower: ]

				if len(entries) < 30:
					send_append_entries(entries, replica_id)
				last_heartbeat[follower_index] = time.time()
			else:
				# Sends heartbeat if we need it
				if time_since_in_ms > time_out_threshold:
					send_append_entries([], replica_id)
					last_heartbeat[follower_index] = time.time()

			follower_index += 1
		# Increments the commit index if the majority of replicas agree
		highest_match = highest_agreed_match_index()



		if highest_match > commit_index and highest_match < len(log) and log[highest_match][0] is current_term:

			#Confirm all messages between last commit index and this one
			to_confirm = log[commit_index + 1: highest_match + 1]
			for entry in to_confirm:
				#Actually apply it to the state machine now
				state_machine[entry[1]] = entry[2]
				send_put_confirmation(entry[3], entry[4])

			commit_index = highest_match

	else:


	# Get rid of the temps if the election's not ongoing

		if not election_season:

			for temp in election_temp_storage:
				temp['leader'] = voted_for
				sock.send(json.dumps(temp))
			election_temp_storage = []


		# If this follower is behind the times,
		# Apply the next log item to the state machine
		while commit_index > last_applied:
			last_applied += 1
			entry = log[last_applied]
			key = entry[1]
			val = entry[2]
			state_machine[key] = val

		time_since_last_heartbeat = time.time() - last_heartbeat_to_me
		time_since_in_ms = time_since_last_heartbeat * 1000

		# If you are a follower, wait 150-300ms before starting
		# elections
		election_modifier = random.randint(100,200)


		if time_out_threshold + election_modifier < time_since_in_ms:
			start_election()

	ready = select.select([sock], [], [], 0.1)[0]

	if sock in ready:
		msg_raw = sock.recv(32768)

		if len(msg_raw) == 0: continue
		msg = json.loads(msg_raw)

		if 'append' in msg['type']:
			leader_term = msg['term']
			leader_id = msg['leader']
			prev_log_index = msg['prev_log_index']
			prev_log_term = msg['prev_log_term']
			entries = msg['entries']
			leader_commit = msg['leader_commit']
			dest = msg['src']
			response = recieve_append_entries(leader_term, leader_id, prev_log_index, prev_log_term, entries, leader_commit)
			send_append_entries_response(response, dest)
			last_heartbeat_to_me = time.time()

		if 'app_response' in msg['type']:
			term = msg['term']
			success = msg['ok']
			nextindex = msg['nextIndex']
			src_id = msg['src']
			recieve_append_response(term, success, nextindex, src_id)


		# For now, ignore get() and put() from clients
		if msg['type'] in ['get', 'put']:

			#Redirect if a follower recieves the request
			if not is_leader:

				# If I'm not the leader but I voted for me,
				# it's election season. Fail these
				if election_season:
					# Leader field is missing
					# Store this message, to send when we
					# have a leader again
					new_msg = {
						'src': my_id,
						'dst': msg['src'],
						'type': 'redirect',
						'leader': 'FFFF',
						'MID': msg['MID'],
						}
					election_temp_storage.append(new_msg)

				else:
					new_msg = {
						'src': my_id,
						'dst': msg['src'],
						'leader': voted_for,
						'type': 'redirect',
						'MID': msg['MID'],
						}
					sock.send(json.dumps(new_msg))

			else:
				if 'get' in msg['type']:

					key = msg['key']
					val = ""
					if key in state_machine.keys():
						val = state_machine[key]
					ok_msg = {
						'src': my_id,
						'dst': msg['src'],
						'leader': my_id,
						'type': 'ok',
						'MID': msg['MID'],
						'value': val
						}
					sock.send(json.dumps(ok_msg))
				if 'put' in msg['type']:
					ok_msg = {
						'src': my_id,
						'dst': msg['src'],
						'leader': my_id,
						'type': 'ok',
						'MID': msg['MID']
						}
					key = msg['key']
					val = msg['value']
					src = msg['src']
					# Add to log
					log.append([current_term, key, val, src, msg['MID']])


		# You just got a vote request for a new leader
		if msg['type'] == 'election':
			candidate_term = msg['term']
			candidate_id = msg['src']
			last_log_index = msg['last_log_index']
			last_log_term = msg['last_log_term']
			resp = recieve_vote_request(candidate_term, candidate_id, last_log_index, last_log_term)
			send_vote_response(resp, candidate_id)
			last_heartbeat_to_me = time.time()

		# You just got a vote response, possibly voting for you!
		if msg['type'] == 'election_vote':
			term = msg['term']
			voted_for_me = msg['vote_granted']
			recieve_vote_response(term, voted_for_me)
			last_heartbeat_to_me = time.time()
